title: Azure DevOps Pro
email: contact@azuredevopspro.com
description: "DevOps is culture, tools are outcome! Learn Azure DevOps, GitOps, CI/CD, and cloud-native engineering."
baseurl: "/azuredevopspro_web_new"
url: "https://ashishrajsrivastava.github.io"

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/


exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - scripts
  - "*.sh"
