title: Azure DevOps Pro
email: contact@azuredevopspro.com
description: "Cloud & GenAI Platform Architect. Expert in CAF, WAF, Azure Landing Zones, and Safe Scale AI Platforms."
baseurl: ""
url: "https://azuredevopspro.com"

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/


exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - scripts
  - "*.sh"
